name: av_media_player
description: "A lightweight media player for flutter. Which uses Texture Widget for video rendering. Backend builts on AVPlayer(ios/macos) and MediaPlayer(Android)."
version: 0.6.2
repository: "https://github.com/xxoo/av_media_player"
issue_tracker: "https://github.com/xxoo/av_media_player/issues"
topics:
  - audio
  - video
  - media
  - player
  - hls

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: any

flutter:
  plugin:
    platforms:
      android:
        package: dev.xx.av_media_player
        pluginClass: AVMediaPlayerPlugin
      ios:
        pluginClass: AVMediaPlayerPlugin
      macos:
        pluginClass: AVMediaPlayerPlugin
