# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+*' # tag-pattern on pub.dev: 'v{{version}}'
  workflow_dispatch:
  
jobs:
  publish:
    permissions:
      id-token: write # Required for authentication using OIDC
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - uses: actions/checkout@v4
        with:
          repository: flutter/flutter
          ref: stable
          path: ../flutter

      - run: sudo apt install -y curl git unzip xz-utils zip libglu1-mesa
      
      - run: export PATH=../flutter/bin:#PATH;flutter pub get;flutter pub publish -f
